import smtplib
from email.mime.multipart import MIMEMultipart 
from email import encoders
from email.header import Header
from email.mime.text import MIMEText
from email.utils import parseaddr, formataddr
from email.mime.application import MIMEApplication
 
#发件人邮箱
sender = "[No-reply] Jiuru Lyu"
asender = f"{sender}<lvjiuru@163.com>"
#收件人邮箱
receiver_1 = "Jiuru Lyu"
areceiver= f"{receiver_1}<lvjiuru@hotmail.com>"
#抄送人邮箱
accer = "Jiuru Lyu"
acc = f'{accer}<lvjiuru@hotmail.com>'
#邮件主题
asubject = '[Alert!] Time to Learn some Python' 
wishes = "Best Regards"
 
#发件人地址
from_addr = "lvjiuru@163.com"
#邮箱密码（授权码）
password="UOGGCLBJQKKWHKXA"
 
#邮件设置
msg = MIMEMultipart()
msg['Subject'] = asubject  
msg['to'] = areceiver  
msg['Cc'] = acc 
msg['from'] = asender
 
#邮件正文
body = f"Dear {receiver_1}, " \
       f"\n\nThis emial is automatically generated by Python 3.6 on Visual Studio Code. \n\n" \
       f"You are receiving this email becuase the sender thinks you should start to learn some coding skills. " \
       f"Reply to this email with evidence of your progress. \n\n" \
       f"Thank you. Hope you enjoy your Thursday. \n\n" \
       f"{wishes},\nJiuru Lyu"
 
#添加邮件正文:
msg.attach(MIMEText(body, 'plain', 'utf-8'))
 
#添加附件
#注意这里的文件路径是斜杠
#xlsxpart = MIMEApplication(open('C:/Users/zhangjunhong/Desktop/这是附件.xlsx', 'rb').read())
#xlsxpart.add_header('Content-Disposition', 'attachment', filename='这是附件.xlsx')
#msg.attach(xlsxpart)    
 
#设置邮箱服务器地址以及端口
smtp_server ="smtp.163.com"
server = smtplib.SMTP(smtp_server, 25)
server.set_debuglevel(1)
 
#登陆邮箱
server.login(from_addr, password)
 
#发送邮件
server.sendmail(from_addr, areceiver.split(',')+acc.split(','), msg.as_string())
 
#断开服务器链接
server.quit()
