---
title: "R Notebook"
output: html_notebook
---


Suppose $y_1,\dots,y_n$ denotes measurements presumed to have come from a continuous pdf $f_Y(y)$. Let $k$ denote the number of $y_i$'s that are less than the median of $f_Y(y)$. If the sample is random, we would expect the difference between $\dfrac{k}{n}$ and $\dfrac{1}{2}$ to be small. More specifically, a $95\%$ confidence interval based on $k$ should contain the value $0.5$.

Let $f_Y(y)=e^{-y}$. The median is $m=0.69315$
```{r}

  args <- commandArgs(trailingOnly = TRUE)
  n <- 10 # Number of random samples
  r <- 3 # Rate of the exponential
  # Check if the rate argument is given
  if (is.na(r)) return ("Please provide a rate and try again.")

  # Start computing
  f <- function(y) pexp(y, rate = r)-0.5
  m <- uniroot(f, lower = 0, upper = 100, tol = 1e-9)$root
  print(paste("For rate ", r, " exponential distribution, the median is equal to ", round(m, 3)))
```
```{r}
  data <- rexp(n, r) # Generate random samples
  data <- round(data, 3) # Round to 3 decimal places
  data <- matrix(data, nrow = 10, ncol = 10) # Turn the data to a matrx
  print(data) # Print the matrix
  k <- sum(data > m) # Count how many entires is bigger than m
  lowerbd <- k/n - 1.96*sqrt((k/n)*(1-k/n)/n)
  upperbd <- k/n + 1.96*sqrt((k/n)*(1-k/n)/n)
  print(paste("The 95% confidence interval for k/n is (",
              round(lowerbd, 3), ", ",
              round(upperbd, 3), ")"))
```